#!/usr/bin/env python3
# -*- coding: utf-8 -*-

if __name__ == '__main__':
    inp_list = list(map(int, input().split()))
    out_list = list()
    if len(inp_list) != 10:
        print("Err")

    for i in inp_list:
        if i % 3 == 0 and i !=0:
            out_list.append(i)
            ind = inp_list.index(i)
    print(out_list)
    print (ind)
    
    # out_list = [i for i in inp_list if i % 3 == 0 and i !=0 ]
    # ind = [inp_list.index(i) for i in inp_list if i % 3 == 0 and i !=0 ]
    # print(out_list)
    # print(ind[-1])
            
